[tool.poetry]
name = "microai"
version = "0.1.0"
description = ""
authors = ["Aleksa Sukovic <sukovic.aleksa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ipykernel = "^6.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
